Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Rearrange this cell to get it to run and properly wrangle the heart disease data

# YOUR COMMENT HERE
X_train = pd.DataFrame(preprocessor.fit_transform(X_train),
                       index=X_train.index,
                       columns=(numeric_features +
                                list(preprocessor.named_transformers_['ohe']
                                     .get_feature_names(categorical_features))))
X_test = pd.DataFrame(preprocessor.transform(X_test),
                      index=X_test.index,
                      columns=X_train.columns)

# YOUR COMMENT HERE
numeric_features = ['age', 'resting_blood_pressure', 'cholesterol',
                    'max_heart_rate_achieved', 'st_depression', 'num_major_vessels']
categorical_features = ['sex', 'chest_pain_type', 'fasting_blood_sugar', 'rest_ecg',
                        'exercise_induced_angina', 'st_slope', 'thalassemia']

# YOUR COMMENT HERE
preprocessor = ColumnTransformer(
    transformers=[
        ('scale', StandardScaler(), numeric_features),
        ('ohe', OneHotEncoder(drop="first"), categorical_features)])

# YOUR COMMENT HERE
heart_df = pd.read_csv('heart_disease.csv', index_col=0)

# YOUR COMMENT HERE
X_train, X_test, y_train, y_test = train_test_split(heart_df.drop(columns='target'),
                                                    heart_df[['target']],
                                                    test_size=0.3,
                                                    random_state=123)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-4526ffd90ad8>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;31m# YOUR COMMENT HERE[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m X_train = pd.DataFrame(preprocessor.fit_transform(X_train),
[0m[1;32m      5[0m                        [0mindex[0m[0;34m=[0m[0mX_train[0m[0;34m.[0m[0mindex[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m                        columns=(numeric_features +

[0;31mNameError[0m: name 'preprocessor' is not defined
NameError: name 'preprocessor' is not defined

